services:
  minio:
    image: minio/minio:minio/minio:RELEASE.2024-06-06T09-36-42Z-cpuv1
    container_name: minio
    restart: always
    ports:
      - "9000:9000" #S3 API
      - "9001:9001" #Console UI
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001"

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local
