services:
  minio:
    image: minio/minio:RELEASE.2024-06-06T09-36-42Z-cpuv1
    ports:
      - "29000:9000" #S3 API
      - "29001:29001" #Console UI
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":29001"
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/psf/NFS/minio_data
  minio_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/psf/NFS/minio_config
