services:
  minio:
    image: minio/minio:RELEASE.2024-06-06T09-36-42Z-cpuv1
    ports:
      - "29000:9000" #S3 API
      - "29001:29001" #Console UI
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Gumon#2024
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    command: server /data --console-address ":29001"
    restart: always
    networks:
      - minio-network

networks:
  minio-network:
    driver: bridge

volumes:
  minio-data:
    driver: local
  minio-config:
    driver: local